"""add patronomic to users

Revision ID: 3479d2730222
Revises: 302b3d127016
Create Date: 2026-06-11 15:01:42.450031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3479d2730222'
down_revision: Union[str, Sequence[str], None] = 'b44ef7afb25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronomic', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patronomic')
    # ### end Alembic commands ###
